openapi: "3.0.3"
info:
  title: Safe Travels' Endpoints
  version: "1.0"
servers:
  - url: https://api.server.test/v1 # TODO: Replace with actual server url
paths:
  /test:
    get:
      responses:
        "200":
          description: OK
